---
title: "ST597 Homework Assignment 1"
author: "Brad Yarbro"
date: "January 26, 2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1
### (a)

```{r, echo=TRUE}
p1a <- c(rep(1,6), rep(3,6), rep(6,6))
p1a <- rep(c(1,3,6), rep(6,3))
p1a
```

### (b)

```{r, echo=TRUE}
p1b <- c(rep(1,5), rep(2,4), rep(3,3), rep(4,2), rep(5,1))
p1b <- rep(1:5, 5:1)
p1b
# or
p1b <- c()
for (i in 1:5){
  v <- c()
  while (length(v) < 6 - i){
    v <- c(v,rep(i, 6 - i))
  }
  p1b <- c(p1b, v)
}
p1b
```

### (c)

```{r, echo=TRUE}
p1c <- rep(c(1,3,6), c(3,1,6))
p1c
```

## Problem 2

```{r, echo=TRUE}
data(Orange)
x <- Orange$age
y <- Orange$circumference

#x <- c(1,2,3,4)
#y <- c(2,4,6,9)

correlation <- t(x - mean(x)) %*% (y - mean(y)) / sqrt(sum((x-mean(x))^2) * sum((y-mean(y))^2))
correlation

cor(x,y)
```

## Problem 3

```{r, echo=TRUE}
samp <- c(4.5, 7.3, 0.017, 12, 15, 8.4, 8.9)

ans <- c(sum(sqrt(abs(samp - mean(samp)))),
         max((samp - median(samp)) ^ 2),
         abs(round(sqrt(samp), 2) ^ 2 - samp))

ans
```

## Problem 4

```{r, echo=TRUE}
data(chickwts)
x <- chickwts$weight
head(x)

MAD <- 1.4826 * median(abs(x - median(x)))
MAD
mad(x)

```

## Problem 5

```{r, echo=TRUE}
s2 <- (sum(x ^ 2) - sum(x) ^ 2 / length(x)) / (length(x) - 1)
s2
var(x)
```

## Problem 6

```{r, echo=TRUE}
ans6 <- sum(rep(5,10) ^ (1:10) / factorial(1:10))
ans6
```









